version: '3'
services:
  web:
    build: .
    container_name: web
    ports:
      - 8080:8080
    volumes:
      - .:/app
  db:
    image: mongo
    container_name: db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
